visage/frontend/controllers.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Showoff - Webbased photo album software

Copyright (c) 2010-2014 by Jochem Kossen <jochem@jkossen.nl>

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

   1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
   2. Redistributions in binary form must reproduce the above
   copyright notice, this list of conditions and the following
   disclaimer in the documentation and/or other materials provided
   with the distribution.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS
BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import json
import os
import re

from flask import Blueprint, current_app, send_from_directory, request, redirect, session, url_for, jsonify, flash, \
    render_template, send_file, abort

import config
from scripts.visage_scripts import update_user_values
from visage.lib import Show, Image, CacheManager
from visage.lib.campaign import model_campaign
from visage.lib.campaign.model_campaign import Campaign, get_campaigns, get_all_campaigns, get_campaign_id, \
    update_pending_table_campaign
from visage.lib.database_manager import prepare_data
from visage.lib.deleted import model_deleted
from visage.lib.photo import model_photo
from visage.lib.photo.model_photo import Photo
from visage.lib.resolve import model_resolve
from visage.lib.resolve.model_resolve import Resolve
from visage.lib.state.model_state import State
from visage.lib.statistics.model_statistics import Statistics, get_votes_description
from visage.lib.user.model_user import User
from visage.lib.vote.model_vote import Vote
import zipfile

from visage_tools import fix_downloads, fix_image, get_rectangle_dlib

frontend = Blueprint('frontend', __name__, template_folder='templates')

service_method = 'azure'


@frontend.route('/login', methods=['POST', 'GET'])
def login():
    error = None

    if request.method == 'POST':

        username = request.form['inputUsername']
        password = request.form['inputPassword']

        user = User(username, password)

        if user.authenticate_user():
            session['logged_in'] = True
            session['inputUsername'] = request.form['inputUsername']
            flash('You were successfully logged in')
            return redirect(url_for('frontend.index'))
        else:
            error = 'Invalid credentials'

    return render_template('login.html', error=error)


@frontend.route('/register', methods=['POST', 'GET'])
def register():
    error = None

    if request.method == 'POST':

        username = request.form['inputUsername']
        email = request.form['inputEmail']
        password = request.form['inputPassword']

        user = User(username, password)
        user.set_email(email)

        if user.register_user():
            session['inputUsername'] = request.form['inputUsername']
            message = 'registered successfully'
            flash(message)
            return redirect(url_for('frontend.index'))

        else:
            error = 'email/username already in use'
            # return message

    return render_template('register.html', error=error)


@frontend.route('/static_files/<path:filename>')
def static_files(filename):
    """Send static files such as style sheets, JavaScript, etc."""
    static_path = os.path.join(frontend.root_path, 'static')
    return send_from_directory(static_path, filename)


@frontend.route('/image/<album>/<filename>/full/', defaults={'size': 'full'})
@frontend.route('/image/<album>/<filename>/<int:size>/')
def get_image(album, filename, size="full"):
    image = Image(album, filename, current_app.config, service_method)
    cache = CacheManager(image, current_app.config)

    cache_path = os.path.expanduser(str(cache.get_path(size)))

    if os.path.exists(cache_path):
        return send_from_directory(*cache.get(size))
    else:
        cache_path_full = os.path.expanduser(str(cache.get_path('full')))
        if os.path.exists(cache_path_full):
            return send_from_directory(*cache.get(size))
        else:
            return 'file not found: {0}'.format(cache_path)

        # fsanda


@frontend.route('/image_face/<album>/<filename>')
def get_image_face(album, filename):
    from io import BytesIO
    from PIL import Image as PilImage, ImageDraw

    # fix image

    if config.FIX_IMAGES:
        fix_image(filename)

    path_file = os.path.join(config.ALBUMS_DIR, album, filename)

    if os.path.exists(path_file):

        image = Image(album, filename, current_app.config, service_method)

        list_coordinates_rectangle = image.get_face_rectangle_coordinates()

        im = PilImage.open(os.path.join(config.ALBUMS_DIR, album, filename))

        '''
        
        for orientation in ExifTags.TAGS.keys():
            if ExifTags.TAGS[orientation]=='Orientation':
                break

        exif = dict(im._getexif().items())

        if exif[orientation] == 3:
            im = im.rotate(180, expand=True)
        elif exif[orientation] == 6:
            im = im.rotate(270, expand=True)
        elif exif[orientation] == 8:
            im = im.rotate(90, expand=True)
        im.save(path_file)
        im.close()
        
        '''

        draw = ImageDraw.Draw(im)

        if list_coordinates_rectangle is not None:

            for rec in list_coordinates_rectangle:
                draw.rectangle(xy=rec, outline='green')

        del draw

        byte_io = BytesIO()
        im.save(byte_io, 'PNG')
        byte_io.seek(0)

        return send_file(byte_io, mimetype='image/png')

    else:
        print('file not found')

        # create file not found image

        # byte_io = BytesIO()
        # im.save(byte_io, 'PNG')
        # byte_io.seek(0)

        return 'file not found'


@frontend.route('/<campaign_id>/<filename>.html/<gender_edit>')
def image_page(campaign_id, filename, gender_edit):
    if session.get('inputUsername'):
        user = str(session['inputUsername'])
    else:
        return 'Session expired'

    if model_deleted.check_deleted(os.path.splitext(filename)[0]):
        return jsonify(result='Image was deleted')

    campaign = Campaign(campaign_id=campaign_id)

    album = campaign.get_age()

    image = Image(album, filename, current_app.config, service_method)

    show = Show(user=user, campaign=campaign)

    # get tag image from database with filename

    # get url from database with filename

    title = image.get_title()

    description = image.get_description()

    tag_list = image.get_tags()

    url = image.get_url()

    s_edit_gender = str(gender_edit)

    edit_gender = True if s_edit_gender == 'True' else False

    # if image is deleted direct to page deletion

    return render_template(
        'image.html',
        album=album,
        filename=filename,
        show=show,
        title=title,
        description=description,
        tags=tag_list,
        url=url,
        date_metadata=image.get_date(),
        gender_edit=edit_gender
    )


@frontend.route('/list/<campaign_id>.html')
def list_album(campaign_id):
    if session.get('inputUsername'):
        user = str(session['inputUsername'])
    else:
        return 'Session expired: cannot retrieve user'

    campaign = Campaign(campaign_id=campaign_id)

    age = campaign.get_age()

    if str.isdigit(str(age)):
        # control session expiry

        show = Show(user=user, campaign=campaign)
        show.set_method(service_method)

        new_gender = 'male' if str(campaign.get_gender()) == 'female' else 'female'

        new_campaign = Campaign(age=campaign.get_age(), gender=new_gender, type_faces='single')
        new_campaign.set_id()

        show.load(config.THUMBNAILS_PER_PAGE)

        data = show.get_data()

        dict_data = dict(data.get('dict_data'))

        ext = re.compile(".(jpg|png|gif|bmp)$", re.IGNORECASE)
        album_dir = os.path.join(current_app.config['ALBUMS_DIR'], str(age))

        all_files = [f for f in os.listdir(album_dir) if ext.search(f)]
        all_files.sort()

        # shuffled_files = random.sample(dict_data.keys(), len(dict_data))
        # files = shuffled_files

        files = dict_data

        completed = 0 if session.get('completed') is None else session.get('completed')

        return render_template(
            'list.html',
            show=show,
            files=files,
            dictionary_data=dict_data, completed=completed)


# shows first page of all images (we will show all)
@frontend.route('/campaign/<campaign_id>.html')
def show_album(campaign_id):
    """Render first page of album"""

    return list_album(campaign_id)


@frontend.route('/')
def index():
    latest_campaigns = None

    if session.get('logged_in'):
        latest_campaigns = get_campaigns(config.LATEST_CAMPAIGN_SIZE)

    return render_template('index.html', campaigns=latest_campaigns)


# shows cover of album gallery
@frontend.route('/campaign/<campaign_id>', methods=['GET', 'POST'])
def show_album_gallery(campaign_id=None):
    if session.get('inputUsername'):
        user = str(session['inputUsername'])
    else:
        return 'session expired'  # todo send to error page

    if session.get('completed'):

visage/frontend/templates/campaigns.html
{% extends "layout.html" %}
{% block body %}

    <p>
    * The number of photos left are not completely accurate or not available, they are updated every midnight (GMT 0).
        However, you can update the info by pressing "Update" but the process takes between 3 to 5 minutes.
        For a specific number of photos left, please visit the related campaign.
    </p>
    <p>
        <a href="{{ url_for('frontend.update_number_images')}}">Update</a>
    </p>



    <table class="campaigns">
        <caption><b>Campaigns Available</b></caption>
        <tr>
            <th>#</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Number Photos Left</th>
            <th>Type</th>
            <th>Last Access</th>
        </tr>

        {% for row in campaigns %}
            <tr>
                <td> {{ loop.index }} </td>
                <td>
                    <a href="{{ url_for('frontend.show_album_gallery', campaign_id = row['_id']) }}">
                        {{ row['age'] }}
                </a>
                </td>
                <td>
                    {{ row['gender'] }}
                </td>

                <td>
                    {{ row['number_images'] if row['number_images'] != None else 'Not Available' }}
                </td>

                <td>
                    {{ row['type_faces'] }}
                </td>
                <td>
                    {{ row['last_access'] }}
                </td>
            </tr>
        {% endfor %}
    </table>

{% endblock %}

visage/frontend/templates/image.html
{% block title %}Filename: {{ filename }}{% endblock %}
{% block body %}

    <p>
    <label>Album: {{ album }}</label>
    </p>

    <p>Available image sizes:
        {% for size in config.ALLOWED_SIZES %}
            {% if size != 'full' %}
                <a href="{{ url_for('frontend.get_image', album=album, size=size, filename=filename) }}">{{ size }}</a>
            {% else %}
                <a href="{{ url_for('frontend.get_image', album=album, filename=filename, size='full') }}">{{ size }}</a>
            {% endif %}

            {% if not loop.last %}
            {% endif %}
        {% endfor %}

    <a href="{{ url_for('frontend.rotate', album=album, filename=filename) }}"><img src="{{ url_for('frontend.static_files', filename='repeat_arrow.png') }}"></a>

    </p>

    <img src="{{ url_for('frontend.get_image_face', album=album, filename=filename)}}" alt="{{ filename }}" height="auto" width="100%"/>

    {% if gender_edit %}
        <table width="100%">
        <tr>
            <td>
                   <a class="button confirmation" href={{ url_for('frontend.change_gender', filename=filename) }}>(Click here if gender is incorrect...)</a>
            </td>
            <td>
                    <a class="button confirmation" href={{ url_for('frontend.delete_image', filename=filename) }} >(Click here if you want to permanently delete the photo...)</a>
            </td>
        </tr>
        </table>
    {% endif %}

    <p>
        Title: {{ title }}
    </p>

    <p>
        Description: {{ description }}
    </p>

    <p>
        Metadata date download: {{ date_metadata }}
    </p>

    <p>

    Tags:

    <table border="1">
            {% for item in tags %}
                <tr><td>{{ item }}</td></tr>
            {% endfor %}
    </table>

    </p>

    <p>
        FLICKR URL: <a href="{{ url }}">{{ url }}</a>
    </p>
    <script src="{{ url_for('frontend.static_files', filename='showoffuser.js') }}">
    </script>

    <script>
    var elems = document.getElementsByClassName('confirmation');
    var confirmIt = function (e) {
        if (!confirm('Are you sure?')) e.preventDefault();
    };
    for (var i = 0, l = elems.length; i < l; i++) {
        elems[i].addEventListener('click', confirmIt, false);
    }
    </script>
{% endblock %}

visage/frontend/templates/index.html
{% extends "layout.html" %}
{% block body %}
    <h3>Welcome to Visage</h3>

    {% if session['logged_in'] %}
        <p>Please click on the campaign links or query your choice and press <b>GO:</b></p>
    {% else %}
        <p>Please login if you have an existing account or register.</p>
    {% endif %}

    <div align="center">
    {% if session['logged_in'] %}

        <form action="{{ url_for('frontend.show_album_gallery', campaign_id=-1) }}" method="post">
            <div>
                <table border="1">
                    <caption><b>Query</b></caption>
                    <tr>
                        <td>
                            <b>Age:</b><br>
                            <input title="age" type="number" value="1" name="campaign_age" min="0" max="120">
                        </td>
                        <td>
                            <b>Gender:</b><br>
                            <input title="both" type="radio" name="campaign_gender" value="both" disabled> Both<br>
                            <input title="male" type="radio" name="campaign_gender" value="male" checked> Male<br>
                            <input title="female" type="radio" name="campaign_gender" value="female"> Female
                        </td>
                        <td>
                            <b>Type Faces</b>:<br>
                            <input title="single" type="radio" name="campaign_type_faces" value="single" checked> Single<br>
                            <input title="multiple" type="radio" name="campaign_type_faces" value="multiple"> Multiple<br>
                            <input title="others" type="radio" name="campaign_type_faces" value="others"> Other
                        </td>
                    </tr>
                    <tr>
                        <td>
                        <input type="submit" value="GO" class="navbutton">
                        </td>
                    </tr>
                </table>
            </div>
        </form>
        <br>
        <br>
        <table class="campaigns">
            <caption><b>Latest Campaigns accessed</b></caption>
            <tr>
                <th>Age</th>
                <th>Gender</th>
                <th>Type</th>
                <th>Last Access</th>
            </tr>

            {% for row in campaigns %}
                <tr>
                    <td>
                        <a href="{{ url_for('frontend.show_album_gallery', campaign_id = row['_id']) }}">
                            {{ row['age'] }}
                    </a>
                    </td>
                    <td>
                        {{ row['gender'] }}
                    </td>
                    <td>
                        {{ row['type_faces'] }}
                    </td>
                    <td>
                        {{ row['last_access'] }}
                    </td>
                </tr>
            {% endfor %}
        </table>

    {% endif %}
    </div>
{% endblock %}

visage/frontend/templates/layout_showoff.html
<!DOCTYPE html>
<html lang="en">
        {% block head %}
            <meta charset="utf-8">
            <meta http-equiv="X-UA-Compatible" content="IE=edge">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>{% block title %}{{ config.TITLE }}{% endblock %}</title>
            <link rel="stylesheet" href="{{ url_for('frontend.static_files', filename='bootstrap/css/bootstrap.min.css') }}" type="text/css" />
            <link rel="stylesheet" href="{{ url_for('frontend.static_files', filename='style.css') }}" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% endblock %}

        <div style="background-color: #3c3c3c">
        {% block posthead %}

        {% endblock %}
        </div>

        {% block body %}

        {% endblock %}

        <div class="container">
            <div class="footer">
            </div>
        </div>
        <script type="text/javascript" src="{{ url_for('frontend.static_files', filename='jquery.js') }}"></script>
        <script type="text/javascript" src="{{ url_for('frontend.static_files', filename='bootstrap/js/bootstrap.min.js') }}"></script>
        {% block postfooter %}{% endblock %}
</html>

visage/frontend/templates/list.html
{% extends "layout_showoff.html" %}
{% block title %} voting - VisAGe{% endblock %}
{% block posthead %}
    <div class="navbar">

        <a href="{{ url_for('frontend.index') }}" title="Home">Home</a>
        {% if show.get_campaign().get_type_faces() == 'single' %}
            <a href="{{ url_for('frontend.vote', campaign_id=show.get_campaign().get_id(), completed = session.get('completed')|int + show.data['files']|length)}}" title="Vote">Vote</a>
        {% else %}
            <a href="#" title="Not Available">Vote</a>
        {% endif %}
        <a href="{{ url_for('frontend.logout') }}" title="Logout">Logout</a>
        <a href="#" class="toggle-all" title="add/remove" data-value="yes"></a>

        <div style="color: white; float: right;">
        <table>
            <tr>
                <td>
                    <progress id="progressVote" value="{{ completed }}" max={{ session['total_images'] }} style="background:white"></progress></td>
                </td>
                <td width="100">
                </td>
                <td>
                    <b>Age :</b> {{ show.get_campaign().get_age()}}
                </td>
                <td width="100">
                </td>
                <td>
                    <b> Gender :</b>
                    <label id="gender_campaign">{{ show.get_campaign().get_gender() }}</label>
                </td>
                <td width="100">
                </td>
                <td>
                    <b>Type :</b>
                    <label id="faces_campaign">{{ show.get_campaign().get_type_faces() }}</label>
                </td>
                <td width="100">
                </td>
            </tr>
            <tr>
                <td>
                    <b>Completed :</b> {{ completed }}/{{ session['total_images'] }}
                </td>
                <td width="100">    </td>
                <td>
                    <b>User :</b> {{ session['inputUsername'] }}
                </td>
        </tr>
        </table>
    </div>
    </div>



{% endblock %}

{% block body %}
    <div>
        {% for message in get_flashed_messages() %}
            <div class="flash">{{ message }}</div>
        {% endfor %}

        {% for filename in files %}
        <div id="div_{{ filename }}" class="gallery thumbnail {% if filename in show.data['files'] and filename not in show.data['removed'] %} published{% endif %}">
            <div>
                <table>
                    <tr>
                        <td>
                <a id="{{ filename }}" href="#" class="toggle-publish" title="add/remove"
                   data-filename="{{ filename }}"
                   data-value="{% if filename in show.data['files'] and filename not in show.data['removed'] %}yes{% else %}no{% endif %}"
                   data-faces="{{ dictionary_data[filename]['type_faces'] }}"></a>
                        </td>
                        <td width="50"></td>
                        <td>
                <a id="btn_gender_{{ filename }}" href="#" class="toggle-gender" title="gender"
                   data-filename="{{ filename }}"
                   data-value="{{ dictionary_data[filename]['gender'] }}"
                   data-faces="{{ dictionary_data[filename]['type_faces'] }}">
                </a>
                        </td>
                    <td width="50"></td>
                        <td>
                <a id="btn_faces_{{ filename }}" href="#" class="toggle-faces" title="faces"
                   data-filename="{{ filename }}"
                   data-value="{{ dictionary_data[filename]['type_faces'] }}">
                </a>
                        </td>
                    </tr>
                </table>



                <a target="_blank" href="{{ url_for('frontend.image_page', campaign_id=show.get_campaign().get_id(), filename=filename, gender_edit=False) }}" title="more information and sizes">
                    <img src="{{ url_for('frontend.get_image', album=show.get_campaign().get_age(), filename=filename, size=config.THUMBNAIL_SIZE) }}" alt="{{ filename }}"/>
                </a>
            </div>
        </div>

    {% endfor %}
</div>
{% endblock %}

{% block postfooter %}
<script type="text/javascript">
    $(document).ready(function() {
    var cfg = {
        'base_url': '{{ url_for('frontend.toggle_publish', album=show.get_campaign().get_id()) }}'
    };

    var images = [ {% for filename in all_files %}'{{ filename }}'{% if not loop.last %}, {% endif %}{% endfor %} ];

    SHOWOFF.init(cfg, images);
    });

</script>
<script src="{{ url_for('frontend.static_files', filename='showoffuser.js') }}"></script>
{% endblock %}

visage/frontend/templates/register.html
{% extends "layout.html" %}
{% block body %}
    <h1>Register</h1>
    <p>This is the register page</p>
    {% if error %}
    <p class=error><strong>Error:</strong> {{ error }}
    {% endif %}

    <div class="jumbotron">
        <form class="form-signin" method=POST action="{{ url_for('frontend.register') }}">
            <label for="inputUsername" class="sr-only">Username</label>
            <input type="name" name="inputUsername" id="inputUsername" class="form-control" placeholder="Username" required autofocus>
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="email" name="inputEmail" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" name="inputPassword" id="inputPassword" class="form-control" placeholder="Password" required>
            <button id="btnSignUp" class="navbutton" type="submit">Sign up</button>
        </form>
    </div>
{% endblock %}

visage/frontend/templates/search.html
{% extends "layout.html" %}
{% block body %}

<form action="{{ url_for('frontend.search_id')}}" method="POST">
    <div>
        <table border="1">
            <caption><b>POSITIVE OR DISAGREED IMAGE ID</b></caption>
            <tr>
                <td>
                    <input type="search" name="search_id" maxlength="24">
                    <input type="submit" value="GO" class="navbutton">
                </td>
            </tr>
        </table>
    </div>
</form>

{% endblock %}

visage/frontend/templates/statistics_age_range.html
{% extends "layout.html" %}
{% block body %}
    <h3>Detailed Age Range Statistics for Single Faces</h3>

    <button class="accordion">Age Range {{ statistics.get_age_min(), statistics.get_age_max() }}</button>
    <div class="panel">
        <table class="campaigns">
            <thead>
                <tr>
                    <th>Age</th>
                    <th>Metadata</th>
                    <th>Downloaded</th>
                    <th colspan="2">Processed Azure</th>
                    <th style="color:green" colspan="3">Voted Positively</th>
                    <th style="color:gray">Missing Votes</th>
                    <th style="color: red" colspan="3">Disagreed Votes</th>
                </tr>
                <tr>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th>Total</th>
                    <th>Single Faces</th>
                    <th style="color:green">Total</th>
                    <th style="color:green">Male</th>
                    <th style="color:green">Female</th>
                    <th style="color:grey">Total</th>
                    <th style="color:red">Total</th>
                    <th style="color:red">Male</th>
                    <th style="color:red">Female</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td>Total:</td>
                    <td>{{ sums.get('metadata') }}</td>
                    <td>{{ sums.get('downloads') }}</td>
                    <td>{{ sums.get('azure') }}</td>
                    <td>{{ sums.get('azure_single_faces') }}</td>
                    <td>{{ sums.get('votes_three') }}</td>
                    <td>{{ sums.get('votes_value_positive_male') }}</td>
                    <td>{{ sums.get('votes_value_positive_female') }}</td>
                    <td>{{ sums.get('votes_missing') }}</td>
                    <td>{{ sums.get('votes_disagreed') }}</td>
                    <td>{{ sums.get('votes_disagreed_male') }}</td>
                    <td>{{ sums.get('votes_disagreed_female') }}</td>
                </tr>
            </tfoot>
            <tbody>

                {% for i in range(statistics.get_age_min(), statistics.get_age_max() + 1) %}
                    <tr>
                        <td>{{ i }}</td>
                        <td>{{ table[i].get('metadata') }}</td>
                        <td>{{ table[i].get('downloads') }}</td>
                        <td>{{ table[i].get('azure') }}</td>
                        <td>{{ table[i].get('azure_single_faces') }}</td>
                        <td style="color: green">{{ table[i].get('votes_three') }}</td>
                        <td style="color: green">
                            {% if table[i].get('votes_value_positive_male') != 0 %}
                                <a href="{{ url_for('frontend.positive', age=i, gender='male', votes=3, files=table[i].get('images')) }}">{{ table[i].get('votes_value_positive_male') }}</a>
                            {% else %}
                                0
                            {% endif %}
                        </td>
                        <td style="color: green">
                            {% if table[i].get('votes_value_positive_female') != 0 %}
                                <a href="{{ url_for('frontend.positive', age=i, gender='female', votes=3) }}">{{ table[i].get('votes_value_positive_female') }}</a>
                            {% else %}
                                0
                            {% endif %}
                        </td>
                        <td style="color:grey">{{ table[i].get('votes_missing') }}</td>


                        <td style="color:red">{{ table[i].get('votes_disagreed') }}</td>

                        <td style="color:red">
                            {% if table[i].get('votes_disagreed_male') != 0 %}
                                <a href="{{ url_for('frontend.show_disagreed', age=i, gender='male') }}"> {{ table[i].get('votes_disagreed_male') }}</a>
                            {% else %}
                                0
                            {% endif %}
                        </td>


                        <td style="color:red">
                            {% if table[i].get('votes_disagreed_female') != 0 %}
                                <a href="{{ url_for('frontend.show_disagreed', age=i, gender='female') }}"> {{ table[i].get('votes_disagreed_female') }}</a>
                            {% else %}
                                0
                            {% endif %}
                        </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script>
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
            });
        }
    </script>

{% endblock %}

visage/frontend/templates/statistics_general.html
{% extends "layout.html" %}
{% block body %}
    <h3>General Statistics for Single Faces</h3>
    <button class="accordion">General</button>
    <div class="panel">
        <table>
            <tr>
                <td>Total Photos Metadata Available:</td>
                <td>{{ statistics.get_photos_metadata() }}</td>
            </tr>
            <tr>
                <td>Total Photos Downloaded:</td>
                <td>{{ statistics.get_photos_download() }}</td>
            </tr>
            <tr>
                <td>Total Photos Processed Azure:</td>
                <td>{{ statistics.get_photos_azure() }}</td>
            </tr>
        </table>
    </div>

    <script>
        var acc = document.getElementsByClassName("accordion");
        var i;

        for (i = 0; i < acc.length; i++) {
            acc[i].addEventListener("click", function() {
                this.classList.toggle("active");
                var panel = this.nextElementSibling;
                if (panel.style.display === "block") {
                    panel.style.display = "none";
                } else {
                    panel.style.display = "block";
                }
            });
        }
    </script>

{% endblock %}